# Required
version: 2

# Image to use
build:
  os: CentOS-7
  image: testing

# Configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
